<a href="https://colab.research.google.com/github/santoshdhalwalkar/DataAcq_wrangling/blob/main/dataAcq_Wrangling.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive

In [2]:
drive.mount("/content/drive")

Mounted at /content/drive


In [3]:
import pandas as pd
import numpy as np
import warnings
import datetime
warnings.filterwarnings("ignore")

In [82]:
data1=pd.read_excel("/content/drive/MyDrive/DatacquisitiondataWrangling/dataset_1.xlsx")

In [83]:
data1

instant     dteday  season  yr  mnth  hr  holiday  weekday  weathersit  \
0          1 2011-01-01       1   0     1   0    False        6           1   
1          2 2011-01-01       1   0     1   1    False        6           1   
2          3 2011-01-01       1   0     1   2    False        6           1   
3          4 2011-01-01       1   0     1   3    False        6           1   
4          5 2011-01-01       1   0     1   4    False        6           1   
..       ...        ...     ...  ..   ...  ..      ...      ...         ...   
605      606 2011-01-28       1   0     1  11    False        5           3   
606      607 2011-01-28       1   0     1  12    False        5           3   
607      608 2011-01-28       1   0     1  13    False        5           3   
608      609 2011-01-28       1   0     1  14    False        5           3   
609      610 2011-01-28       1   0     1  15    False        5           2   

     temp  
0    0.24  
1    0.22  
2    0.22  
3    0.24  
4    0.24  
..    ...  
605  0.18  
606  0.18  
607  0.18  
608  0.22  
609  0.20  

[610 rows x 10 columns]

In [84]:
data1.shape

(610, 10)

In [85]:
data1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 610 entries, 0 to 609
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype         
---  ------      --------------  -----         
 0   instant     610 non-null    int64         
 1   dteday      610 non-null    datetime64[ns]
 2   season      610 non-null    int64         
 3   yr          610 non-null    int64         
 4   mnth        610 non-null    int64         
 5   hr          610 non-null    int64         
 6   holiday     610 non-null    bool          
 7   weekday     610 non-null    int64         
 8   weathersit  610 non-null    int64         
 9   temp        610 non-null    float64       
dtypes: bool(1), datetime64[ns](1), float64(1), int64(7)
memory usage: 43.6 KB


### In below code convert dteday dtype datetime to int format before column show date in this format 2011-01-01 after convtering to int it shows like this 20110101

In [86]:
data1['dteday'] = pd.to_datetime(data1['dteday']).dt.strftime('%Y%m%d').astype(int)


In [87]:
data1.info()
data1

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 610 entries, 0 to 609
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   instant     610 non-null    int64  
 1   dteday      610 non-null    int64  
 2   season      610 non-null    int64  
 3   yr          610 non-null    int64  
 4   mnth        610 non-null    int64  
 5   hr          610 non-null    int64  
 6   holiday     610 non-null    bool   
 7   weekday     610 non-null    int64  
 8   weathersit  610 non-null    int64  
 9   temp        610 non-null    float64
dtypes: bool(1), float64(1), int64(8)
memory usage: 43.6 KB


instant    dteday  season  yr  mnth  hr  holiday  weekday  weathersit  \
0          1  20110101       1   0     1   0    False        6           1   
1          2  20110101       1   0     1   1    False        6           1   
2          3  20110101       1   0     1   2    False        6           1   
3          4  20110101       1   0     1   3    False        6           1   
4          5  20110101       1   0     1   4    False        6           1   
..       ...       ...     ...  ..   ...  ..      ...      ...         ...   
605      606  20110128       1   0     1  11    False        5           3   
606      607  20110128       1   0     1  12    False        5           3   
607      608  20110128       1   0     1  13    False        5           3   
608      609  20110128       1   0     1  14    False        5           3   
609      610  20110128       1   0     1  15    False        5           2   

     temp  
0    0.24  
1    0.22  
2    0.22  
3    0.24  
4    0.24  
..    ...  
605  0.18  
606  0.18  
607  0.18  
608  0.22  
609  0.20  

[610 rows x 10 columns]

In [88]:
data1['weathersit'].unique()

array([1, 2, 3, 4])

In [89]:
data1['weathersit'].value_counts()

weathersit
1    368
2    194
3     47
4      1
Name: count, dtype: int64

In [90]:
data1['season'].unique()

array([1])

In [91]:
data1['season'].value_counts()

season
1    610
Name: count, dtype: int64

In [92]:
data1['temp'].unique()


array([0.24, 0.22, 0.2 , 0.32, 0.38, 0.36, 0.42, 0.46, 0.44, 0.4 , 0.34,
       0.3 , 0.26, 0.16, 0.14, 0.18, 0.12, 0.28, 0.1 , 0.08, 0.06, 0.04,
       0.02])

In [93]:
data1.isnull()

instant  dteday  season     yr   mnth     hr  holiday  weekday  \
0      False   False   False  False  False  False    False    False   
1      False   False   False  False  False  False    False    False   
2      False   False   False  False  False  False    False    False   
3      False   False   False  False  False  False    False    False   
4      False   False   False  False  False  False    False    False   
..       ...     ...     ...    ...    ...    ...      ...      ...   
605    False   False   False  False  False  False    False    False   
606    False   False   False  False  False  False    False    False   
607    False   False   False  False  False  False    False    False   
608    False   False   False  False  False  False    False    False   
609    False   False   False  False  False  False    False    False   

     weathersit   temp  
0         False  False  
1         False  False  
2         False  False  
3         False  False  
4         False  False  
..          ...    ...  
605       False  False  
606       False  False  
607       False  False  
608       False  False  
609       False  False  

[610 rows x 10 columns]

In [94]:
data1.isnull().sum()

instant       0
dteday        0
season        0
yr            0
mnth          0
hr            0
holiday       0
weekday       0
weathersit    0
temp          0
dtype: int64

In [95]:
data1

instant    dteday  season  yr  mnth  hr  holiday  weekday  weathersit  \
0          1  20110101       1   0     1   0    False        6           1   
1          2  20110101       1   0     1   1    False        6           1   
2          3  20110101       1   0     1   2    False        6           1   
3          4  20110101       1   0     1   3    False        6           1   
4          5  20110101       1   0     1   4    False        6           1   
..       ...       ...     ...  ..   ...  ..      ...      ...         ...   
605      606  20110128       1   0     1  11    False        5           3   
606      607  20110128       1   0     1  12    False        5           3   
607      608  20110128       1   0     1  13    False        5           3   
608      609  20110128       1   0     1  14    False        5           3   
609      610  20110128       1   0     1  15    False        5           2   

     temp  
0    0.24  
1    0.22  
2    0.22  
3    0.24  
4    0.24  
..    ...  
605  0.18  
606  0.18  
607  0.18  
608  0.22  
609  0.20  

[610 rows x 10 columns]

In [96]:
data1['yr'].unique()

array([0])

### '**yr**' column have array value 0 only. I think yr column is not important so I think I can drop this column


In [97]:
data1.drop(['yr'], axis=1, inplace=True)
data1

instant    dteday  season  mnth  hr  holiday  weekday  weathersit  temp
0          1  20110101       1     1   0    False        6           1  0.24
1          2  20110101       1     1   1    False        6           1  0.22
2          3  20110101       1     1   2    False        6           1  0.22
3          4  20110101       1     1   3    False        6           1  0.24
4          5  20110101       1     1   4    False        6           1  0.24
..       ...       ...     ...   ...  ..      ...      ...         ...   ...
605      606  20110128       1     1  11    False        5           3  0.18
606      607  20110128       1     1  12    False        5           3  0.18
607      608  20110128       1     1  13    False        5           3  0.18
608      609  20110128       1     1  14    False        5           3  0.22
609      610  20110128       1     1  15    False        5           2  0.20

[610 rows x 9 columns]

data1.to_excel("/content/drive/MyDrive/DatacquisitiondataWrangling/dataset_1.xlsx")
data1

In [98]:
data1['holiday'].unique()

array([False,  True])

In [99]:
data1['weekday'].unique()

array([6, 0, 1, 2, 3, 4, 5])

In [100]:
data1['weekday'].value_counts()

weekday
6    95
0    94
1    93
5    85
3    84
2    80
4    79
Name: count, dtype: int64

In [103]:
data1['weathersit'].unique()

array([1, 2, 3, 4])

In [102]:
data1['weathersit'].value_counts()

weathersit
1    368
2    194
3     47
4      1
Name: count, dtype: int64

In [101]:
data1['holiday'].unique()

array([False,  True])

In [105]:
holiday_data1 = data1[data1['holiday'] == True]
holiday_data1=holiday_data1[['weathersit', 'hr', 'temp', 'dteday','holiday']]
holiday_data1

weathersit  hr  temp    dteday  holiday
372           2   0  0.20  20110117     True
373           2   1  0.20  20110117     True
374           2   2  0.18  20110117     True
375           2   3  0.18  20110117     True
376           2   4  0.18  20110117     True
377           2   5  0.18  20110117     True
378           2   6  0.18  20110117     True
379           2   7  0.16  20110117     True
380           2   8  0.16  20110117     True
381           2   9  0.16  20110117     True
382           2  10  0.16  20110117     True
383           2  11  0.16  20110117     True
384           2  12  0.18  20110117     True
385           2  13  0.18  20110117     True
386           2  14  0.18  20110117     True
387           2  15  0.20  20110117     True
388           2  16  0.20  20110117     True
389           1  17  0.20  20110117     True
390           2  18  0.18  20110117     True
391           3  19  0.18  20110117     True
392           3  20  0.16  20110117     True
393           3  21  0.16  20110117     True
394           3  22  0.14  20110117     True
395           3  23  0.16  20110117     True

In [26]:
holiday_data1['weathersit'].unique()

array([2, 1, 3])

In [27]:
holiday_data1['weathersit'].value_counts()

weathersit
2    18
3     5
1     1
Name: count, dtype: int64

### on holiday user like to go on ride and praticular when weathersit is 2 with maximum ride 18 hrs ride

In [107]:
holiday_data1.to_excel("/content/drive/MyDrive/DatacquisitiondataWrangling/holiday_data1.xlsx")


In [108]:
hd1=pd.read_excel("/content/drive/MyDrive/DatacquisitiondataWrangling/holiday_data1.xlsx")
hd1

Unnamed: 0  weathersit  hr  temp    dteday  holiday
0          372           2   0  0.20  20110117     True
1          373           2   1  0.20  20110117     True
2          374           2   2  0.18  20110117     True
3          375           2   3  0.18  20110117     True
4          376           2   4  0.18  20110117     True
5          377           2   5  0.18  20110117     True
6          378           2   6  0.18  20110117     True
7          379           2   7  0.16  20110117     True
8          380           2   8  0.16  20110117     True
9          381           2   9  0.16  20110117     True
10         382           2  10  0.16  20110117     True
11         383           2  11  0.16  20110117     True
12         384           2  12  0.18  20110117     True
13         385           2  13  0.18  20110117     True
14         386           2  14  0.18  20110117     True
15         387           2  15  0.20  20110117     True
16         388           2  16  0.20  20110117     True
17         389           1  17  0.20  20110117     True
18         390           2  18  0.18  20110117     True
19         391           3  19  0.18  20110117     True
20         392           3  20  0.16  20110117     True
21         393           3  21  0.16  20110117     True
22         394           3  22  0.14  20110117     True
23         395           3  23  0.16  20110117     True

In [109]:
hd1.drop(['Unnamed: 0'], axis=1, inplace=True)
hd1

weathersit  hr  temp    dteday  holiday
0            2   0  0.20  20110117     True
1            2   1  0.20  20110117     True
2            2   2  0.18  20110117     True
3            2   3  0.18  20110117     True
4            2   4  0.18  20110117     True
5            2   5  0.18  20110117     True
6            2   6  0.18  20110117     True
7            2   7  0.16  20110117     True
8            2   8  0.16  20110117     True
9            2   9  0.16  20110117     True
10           2  10  0.16  20110117     True
11           2  11  0.16  20110117     True
12           2  12  0.18  20110117     True
13           2  13  0.18  20110117     True
14           2  14  0.18  20110117     True
15           2  15  0.20  20110117     True
16           2  16  0.20  20110117     True
17           1  17  0.20  20110117     True
18           2  18  0.18  20110117     True
19           3  19  0.18  20110117     True
20           3  20  0.16  20110117     True
21           3  21  0.16  20110117     True
22           3  22  0.14  20110117     True
23           3  23  0.16  20110117     True

In [126]:
data2=pd.read_excel("/content/drive/MyDrive/DatacquisitiondataWrangling/dataset_2.xlsx")
data2

Unnamed: 0  instant   atemp   hum  windspeed  casual  registered  cnt
0             0        1  0.2879  0.81     0.0000       3          13   16
1             1        2  0.2727  0.80     0.0000       8          32   40
2             2        3  0.2727  0.80     0.0000       5          27   32
3             3        4  0.2879  0.75     0.0000       3          10   13
4             4        5  0.2879  0.75     0.0000       0           1    1
..          ...      ...     ...   ...        ...     ...         ...  ...
605         605      606  0.2121  0.93     0.1045       0          30   30
606         606      607  0.2121  0.93     0.1045       1          28   29
607         607      608  0.2121  0.93     0.1045       0          31   31
608         608      609  0.2727  0.80     0.0000       2          36   38
609         609      610  0.2576  0.86     0.0000       1          40   41

[610 rows x 8 columns]

In [127]:
data2.drop(['Unnamed: 0'], axis=1, inplace=True)
data2

instant   atemp   hum  windspeed  casual  registered  cnt
0          1  0.2879  0.81     0.0000       3          13   16
1          2  0.2727  0.80     0.0000       8          32   40
2          3  0.2727  0.80     0.0000       5          27   32
3          4  0.2879  0.75     0.0000       3          10   13
4          5  0.2879  0.75     0.0000       0           1    1
..       ...     ...   ...        ...     ...         ...  ...
605      606  0.2121  0.93     0.1045       0          30   30
606      607  0.2121  0.93     0.1045       1          28   29
607      608  0.2121  0.93     0.1045       0          31   31
608      609  0.2727  0.80     0.0000       2          36   38
609      610  0.2576  0.86     0.0000       1          40   41

[610 rows x 7 columns]

In [128]:
data2.shape

(610, 7)

In [113]:
data2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 610 entries, 0 to 609
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   instant     610 non-null    int64  
 1   atemp       599 non-null    float64
 2   hum         610 non-null    float64
 3   windspeed   610 non-null    float64
 4   casual      610 non-null    int64  
 5   registered  610 non-null    int64  
 6   cnt         610 non-null    int64  
dtypes: float64(3), int64(4)
memory usage: 33.5 KB


In [129]:
data2.isnull().sum()

instant        0
atemp         11
hum            0
windspeed      0
casual         0
registered     0
cnt            0
dtype: int64

### In dataset2 we find **atemp** have 11 null rows


1.   Try to find percetage if null data of atemp column. if it is not more thab 40% to 50% then we can replace
2.   to replace we find mean and medain which on work better that we replace



In [130]:
data2.isnull().sum()/data2.shape[0]*100

instant       0.000000
atemp         1.803279
hum           0.000000
windspeed     0.000000
casual        0.000000
registered    0.000000
cnt           0.000000
dtype: float64

In [131]:
mean=data2['atemp'].mean()
mean

0.19993489148580967

In [132]:
md=data2['atemp'].median()
md

0.197

In [133]:
data2

instant   atemp   hum  windspeed  casual  registered  cnt
0          1  0.2879  0.81     0.0000       3          13   16
1          2  0.2727  0.80     0.0000       8          32   40
2          3  0.2727  0.80     0.0000       5          27   32
3          4  0.2879  0.75     0.0000       3          10   13
4          5  0.2879  0.75     0.0000       0           1    1
..       ...     ...   ...        ...     ...         ...  ...
605      606  0.2121  0.93     0.1045       0          30   30
606      607  0.2121  0.93     0.1045       1          28   29
607      608  0.2121  0.93     0.1045       0          31   31
608      609  0.2727  0.80     0.0000       2          36   38
609      610  0.2576  0.86     0.0000       1          40   41

[610 rows x 7 columns]

In [134]:
data2['atemp'].fillna(value=md, inplace=True)
data2.isnull().sum()

instant       0
atemp         0
hum           0
windspeed     0
casual        0
registered    0
cnt           0
dtype: int64

## Round the decimal point to uderstand the data easily and better way

In [135]:
updated_data2=data2.round({"atemp":2, "windspeed":2 })
updated_data2

instant  atemp   hum  windspeed  casual  registered  cnt
0          1   0.29  0.81        0.0       3          13   16
1          2   0.27  0.80        0.0       8          32   40
2          3   0.27  0.80        0.0       5          27   32
3          4   0.29  0.75        0.0       3          10   13
4          5   0.29  0.75        0.0       0           1    1
..       ...    ...   ...        ...     ...         ...  ...
605      606   0.21  0.93        0.1       0          30   30
606      607   0.21  0.93        0.1       1          28   29
607      608   0.21  0.93        0.1       0          31   31
608      609   0.27  0.80        0.0       2          36   38
609      610   0.26  0.86        0.0       1          40   41

[610 rows x 7 columns]

updated_data2.to_excel("/content/drive/MyDrive/DatacquisitiondataWrangling/dataset_2.xlsx")

updated_data2

clean_data2=pd.read_excel("/content/drive/MyDrive/DatacquisitiondataWrangling/dataset_2.xlsx")
clean_data2

clean_data2.drop(['Unnamed: 0'], axis=1, inplace=True)
clean_data2

In [136]:
combine_data=pd.merge(data1,updated_data2, on='instant', how='inner')
combine_data

instant    dteday  season  mnth  hr  holiday  weekday  weathersit  temp  \
0          1  20110101       1     1   0    False        6           1  0.24   
1          2  20110101       1     1   1    False        6           1  0.22   
2          3  20110101       1     1   2    False        6           1  0.22   
3          4  20110101       1     1   3    False        6           1  0.24   
4          5  20110101       1     1   4    False        6           1  0.24   
..       ...       ...     ...   ...  ..      ...      ...         ...   ...   
605      606  20110128       1     1  11    False        5           3  0.18   
606      607  20110128       1     1  12    False        5           3  0.18   
607      608  20110128       1     1  13    False        5           3  0.18   
608      609  20110128       1     1  14    False        5           3  0.22   
609      610  20110128       1     1  15    False        5           2  0.20   

     atemp   hum  windspeed  casual  registered  cnt  
0     0.29  0.81        0.0       3          13   16  
1     0.27  0.80        0.0       8          32   40  
2     0.27  0.80        0.0       5          27   32  
3     0.29  0.75        0.0       3          10   13  
4     0.29  0.75        0.0       0           1    1  
..     ...   ...        ...     ...         ...  ...  
605   0.21  0.93        0.1       0          30   30  
606   0.21  0.93        0.1       1          28   29  
607   0.21  0.93        0.1       0          31   31  
608   0.27  0.80        0.0       2          36   38  
609   0.26  0.86        0.0       1          40   41  

[610 rows x 15 columns]

In [137]:
combine_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 610 entries, 0 to 609
Data columns (total 15 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   instant     610 non-null    int64  
 1   dteday      610 non-null    int64  
 2   season      610 non-null    int64  
 3   mnth        610 non-null    int64  
 4   hr          610 non-null    int64  
 5   holiday     610 non-null    bool   
 6   weekday     610 non-null    int64  
 7   weathersit  610 non-null    int64  
 8   temp        610 non-null    float64
 9   atemp       610 non-null    float64
 10  hum         610 non-null    float64
 11  windspeed   610 non-null    float64
 12  casual      610 non-null    int64  
 13  registered  610 non-null    int64  
 14  cnt         610 non-null    int64  
dtypes: bool(1), float64(4), int64(10)
memory usage: 67.4 KB


In [138]:
data3=pd.read_excel("/content/drive/MyDrive/DatacquisitiondataWrangling/dataset_3.xlsx")
data3

instant     dteday  season  yr  mnth  hr  holiday  weekday  weathersit  \
0        620 2011-01-29       1   0     1   1    False        6           1   
1        621 2011-01-29       1   0     1   2    False        6           1   
2        622 2011-01-29       1   0     1   3    False        6           1   
3        623 2011-01-29       1   0     1   4    False        6           1   
4        624 2011-01-29       1   0     1   6    False        6           1   
..       ...        ...     ...  ..   ...  ..      ...      ...         ...   
385      615 2011-01-28       1   0     1  20    False        5           2   
386      616 2011-01-28       1   0     1  21    False        5           2   
387      617 2011-01-28       1   0     1  22    False        5           1   
388      618 2011-01-28       1   0     1  23    False        5           1   
389      619 2011-01-29       1   0     1   0    False        6           1   

     temp   atemp   hum  windspeed  casual  registered  cnt  
0    0.22  0.2273  0.64     0.1940       0          20   20  
1    0.22  0.2273  0.64     0.1642       0          15   15  
2    0.20  0.2121  0.64     0.1343       3           5    8  
3    0.16  0.1818  0.69     0.1045       1           2    3  
4    0.16  0.1818  0.64     0.1343       0           2    2  
..    ...     ...   ...        ...     ...         ...  ...  
385  0.24  0.2273  0.70     0.1940       1          61   62  
386  0.22  0.2273  0.75     0.1343       1          57   58  
387  0.24  0.2121  0.65     0.3582       0          26   26  
388  0.24  0.2273  0.60     0.2239       1          22   23  
389  0.22  0.1970  0.64     0.3582       2          26   28  

[390 rows x 16 columns]

In [139]:
data3.drop(['yr'], axis=1, inplace=True)
data3

instant     dteday  season  mnth  hr  holiday  weekday  weathersit  temp  \
0        620 2011-01-29       1     1   1    False        6           1  0.22   
1        621 2011-01-29       1     1   2    False        6           1  0.22   
2        622 2011-01-29       1     1   3    False        6           1  0.20   
3        623 2011-01-29       1     1   4    False        6           1  0.16   
4        624 2011-01-29       1     1   6    False        6           1  0.16   
..       ...        ...     ...   ...  ..      ...      ...         ...   ...   
385      615 2011-01-28       1     1  20    False        5           2  0.24   
386      616 2011-01-28       1     1  21    False        5           2  0.22   
387      617 2011-01-28       1     1  22    False        5           1  0.24   
388      618 2011-01-28       1     1  23    False        5           1  0.24   
389      619 2011-01-29       1     1   0    False        6           1  0.22   

      atemp   hum  windspeed  casual  registered  cnt  
0    0.2273  0.64     0.1940       0          20   20  
1    0.2273  0.64     0.1642       0          15   15  
2    0.2121  0.64     0.1343       3           5    8  
3    0.1818  0.69     0.1045       1           2    3  
4    0.1818  0.64     0.1343       0           2    2  
..      ...   ...        ...     ...         ...  ...  
385  0.2273  0.70     0.1940       1          61   62  
386  0.2273  0.75     0.1343       1          57   58  
387  0.2121  0.65     0.3582       0          26   26  
388  0.2273  0.60     0.2239       1          22   23  
389  0.1970  0.64     0.3582       2          26   28  

[390 rows x 15 columns]

In [140]:
data3.shape

(390, 15)

In [141]:
update_data3=data3.round({"atemp":2, "windspeed":2 })
update_data3

instant     dteday  season  mnth  hr  holiday  weekday  weathersit  temp  \
0        620 2011-01-29       1     1   1    False        6           1  0.22   
1        621 2011-01-29       1     1   2    False        6           1  0.22   
2        622 2011-01-29       1     1   3    False        6           1  0.20   
3        623 2011-01-29       1     1   4    False        6           1  0.16   
4        624 2011-01-29       1     1   6    False        6           1  0.16   
..       ...        ...     ...   ...  ..      ...      ...         ...   ...   
385      615 2011-01-28       1     1  20    False        5           2  0.24   
386      616 2011-01-28       1     1  21    False        5           2  0.22   
387      617 2011-01-28       1     1  22    False        5           1  0.24   
388      618 2011-01-28       1     1  23    False        5           1  0.24   
389      619 2011-01-29       1     1   0    False        6           1  0.22   

     atemp   hum  windspeed  casual  registered  cnt  
0     0.23  0.64       0.19       0          20   20  
1     0.23  0.64       0.16       0          15   15  
2     0.21  0.64       0.13       3           5    8  
3     0.18  0.69       0.10       1           2    3  
4     0.18  0.64       0.13       0           2    2  
..     ...   ...        ...     ...         ...  ...  
385   0.23  0.70       0.19       1          61   62  
386   0.23  0.75       0.13       1          57   58  
387   0.21  0.65       0.36       0          26   26  
388   0.23  0.60       0.22       1          22   23  
389   0.20  0.64       0.36       2          26   28  

[390 rows x 15 columns]

In [142]:
update_data3['windspeed'].unique()

array([0.19, 0.16, 0.13, 0.1 , 0.09, 0.25, 0.  , 0.28, 0.22, 0.33, 0.3 ,
       0.39, 0.52, 0.55, 0.49, 0.45, 0.36, 0.42, 0.46, 0.58])

In [143]:
update_data3['atemp'].unique()

array([0.23, 0.21, 0.18, 0.2 , 0.24, 0.29, 0.27, 0.32, 0.3 , 0.33, 0.26,
       0.17, 0.14, 0.15, 0.39, 0.12, 0.36, 0.35, 0.11, 0.08, 0.41, 0.42])

In [144]:
update_data3.shape

(390, 15)

In [145]:
update_data3


instant     dteday  season  mnth  hr  holiday  weekday  weathersit  temp  \
0        620 2011-01-29       1     1   1    False        6           1  0.22   
1        621 2011-01-29       1     1   2    False        6           1  0.22   
2        622 2011-01-29       1     1   3    False        6           1  0.20   
3        623 2011-01-29       1     1   4    False        6           1  0.16   
4        624 2011-01-29       1     1   6    False        6           1  0.16   
..       ...        ...     ...   ...  ..      ...      ...         ...   ...   
385      615 2011-01-28       1     1  20    False        5           2  0.24   
386      616 2011-01-28       1     1  21    False        5           2  0.22   
387      617 2011-01-28       1     1  22    False        5           1  0.24   
388      618 2011-01-28       1     1  23    False        5           1  0.24   
389      619 2011-01-29       1     1   0    False        6           1  0.22   

     atemp   hum  windspeed  casual  registered  cnt  
0     0.23  0.64       0.19       0          20   20  
1     0.23  0.64       0.16       0          15   15  
2     0.21  0.64       0.13       3           5    8  
3     0.18  0.69       0.10       1           2    3  
4     0.18  0.64       0.13       0           2    2  
..     ...   ...        ...     ...         ...  ...  
385   0.23  0.70       0.19       1          61   62  
386   0.23  0.75       0.13       1          57   58  
387   0.21  0.65       0.36       0          26   26  
388   0.23  0.60       0.22       1          22   23  
389   0.20  0.64       0.36       2          26   28  

[390 rows x 15 columns]

In [146]:
concat_data = pd.concat([combine_data, update_data3], axis=0)
concat_data

instant               dteday  season  mnth  hr  holiday  weekday  \
0          1             20110101       1     1   0    False        6   
1          2             20110101       1     1   1    False        6   
2          3             20110101       1     1   2    False        6   
3          4             20110101       1     1   3    False        6   
4          5             20110101       1     1   4    False        6   
..       ...                  ...     ...   ...  ..      ...      ...   
385      615  2011-01-28 00:00:00       1     1  20    False        5   
386      616  2011-01-28 00:00:00       1     1  21    False        5   
387      617  2011-01-28 00:00:00       1     1  22    False        5   
388      618  2011-01-28 00:00:00       1     1  23    False        5   
389      619  2011-01-29 00:00:00       1     1   0    False        6   

     weathersit  temp  atemp   hum  windspeed  casual  registered  cnt  
0             1  0.24   0.29  0.81       0.00       3          13   16  
1             1  0.22   0.27  0.80       0.00       8          32   40  
2             1  0.22   0.27  0.80       0.00       5          27   32  
3             1  0.24   0.29  0.75       0.00       3          10   13  
4             1  0.24   0.29  0.75       0.00       0           1    1  
..          ...   ...    ...   ...        ...     ...         ...  ...  
385           2  0.24   0.23  0.70       0.19       1          61   62  
386           2  0.22   0.23  0.75       0.13       1          57   58  
387           1  0.24   0.21  0.65       0.36       0          26   26  
388           1  0.24   0.23  0.60       0.22       1          22   23  
389           1  0.22   0.20  0.64       0.36       2          26   28  

[1000 rows x 15 columns]

In [147]:
concat_data['atemp'].unique()

array([0.29, 0.27, 0.26, 0.2 , 0.35, 0.39, 0.33, 0.42, 0.45, 0.44, 0.41,
       0.23, 0.21, 0.14, 0.11, 0.12, 0.17, 0.18, 0.24, 0.15, 0.32, 0.06,
       0.08, 0.09, 0.3 , 0.03, 0.05, 0.  , 0.02, 0.36])

In [148]:
concat_data['windspeed'].unique()

array([0.  , 0.09, 0.25, 0.28, 0.3 , 0.19, 0.22, 0.13, 0.16, 0.33, 0.45,
       0.36, 0.42, 0.39, 0.1 , 0.49, 0.55, 0.46, 0.52, 0.58])

In [149]:
concat_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1000 entries, 0 to 389
Data columns (total 15 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   instant     1000 non-null   int64  
 1   dteday      1000 non-null   object 
 2   season      1000 non-null   int64  
 3   mnth        1000 non-null   int64  
 4   hr          1000 non-null   int64  
 5   holiday     1000 non-null   bool   
 6   weekday     1000 non-null   int64  
 7   weathersit  1000 non-null   int64  
 8   temp        1000 non-null   float64
 9   atemp       1000 non-null   float64
 10  hum         1000 non-null   float64
 11  windspeed   1000 non-null   float64
 12  casual      1000 non-null   int64  
 13  registered  1000 non-null   int64  
 14  cnt         1000 non-null   int64  
dtypes: bool(1), float64(4), int64(9), object(1)
memory usage: 150.5+ KB


In [150]:
concat_data.isnull().sum()

instant       0
dteday        0
season        0
mnth          0
hr            0
holiday       0
weekday       0
weathersit    0
temp          0
atemp         0
hum           0
windspeed     0
casual        0
registered    0
cnt           0
dtype: int64

In [151]:
concat_data.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...  
385    False
386    False
387    False
388    False
389    False
Length: 1000, dtype: bool

In [152]:
concat_data.duplicated().sum()

0

In [58]:
hoildayride = concat_data[concat_data['holiday'] == True]
hoildayride=hoildayride[['weathersit', 'hr', 'temp', 'dteday','holiday','casual','registered']]
hoildayride

weathersit  hr  temp     dteday  holiday  casual  registered
372           2   0  0.20 2011-01-17     True       1          16
373           2   1  0.20 2011-01-17     True       1          15
374           2   2  0.18 2011-01-17     True       0           8
375           2   3  0.18 2011-01-17     True       0           2
376           2   4  0.18 2011-01-17     True       1           2
377           2   5  0.18 2011-01-17     True       0           1
378           2   6  0.18 2011-01-17     True       0           5
379           2   7  0.16 2011-01-17     True       4           9
380           2   8  0.16 2011-01-17     True       3          30
381           2   9  0.16 2011-01-17     True       8          39
382           2  10  0.16 2011-01-17     True       7          50
383           2  11  0.16 2011-01-17     True       9          55
384           2  12  0.18 2011-01-17     True      10          70
385           2  13  0.18 2011-01-17     True      13          80
386           2  14  0.18 2011-01-17     True      12          74
387           2  15  0.20 2011-01-17     True      21          72
388           2  16  0.20 2011-01-17     True       6          76
389           1  17  0.20 2011-01-17     True       4          67
390           2  18  0.18 2011-01-17     True       7          85
391           3  19  0.18 2011-01-17     True       2          58
392           3  20  0.16 2011-01-17     True       4          29
393           3  21  0.16 2011-01-17     True       3          24
394           3  22  0.14 2011-01-17     True       0          13
395           3  23  0.16 2011-01-17     True       1           3

In [153]:
hoildayride.shape

(24, 7)